name: Build documentation

on:
  # 如果指定了，一旦推送到`main`分支，工作流将自动触发。
  push:
    branches: [ "main" ]
  workflow_dispatch:

# 为工作流提供克隆仓库和创建页面部署的权限
permissions:
  id-token: write
  pages: write

env:
  # 模块名称和ID，用斜杠分隔
  INSTANCE: Writerside/sds
  # 用大写字母替换实例名称
  ARTIFACT: webHelpSDS2-all.zip
  # Writerside docker镜像版本
  DOCKER_VERSION: 232.10165.1
  # 添加下面的变量来上传Algolia索引
  ALGOLIA_ARTIFACT: algolia-indexes-SDS.zip
  # Algolia 应用程序 ID
  ALGOLIA_APP_NAME: NE096NR7D4
  # Algolia 指数名称
  ALGOLIA_INDEX_NAME: dev_pixelcamera
  # Algolia 管理员 API 密钥
  ALGOLIA_KEY: ${{ secrets.ALGOLIA_KEY }}
  # Help instance ID
  CONFIG_JSON_PRODUCT: SDS
  # 帮助实例版本
  CONFIG_JSON_VERSION: Ver 23.11.07


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出仓库
      - name: Checkout repository
        uses: actions/checkout@v3

        # 使用Docker构建Writerside文档
      - name: Build Writerside docs using Docker
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: ${{ env.INSTANCE }}
          artifact: ${{ env.ARTIFACT }}
          docker-version: ${{ env.DOCKER_VERSION }}

        # 上传文档
      - name: Upload documentation
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: |
            artifacts/${{ env.ARTIFACT }}
            artifacts/report.json
          retention-days: 7

      # 添加以下步骤以上传Algolia索引
      - name: Upload algolia-indexes
        uses: actions/upload-artifact@v3
        with:
          name: algolia-indexes
          path: artifacts/${{ env.ALGOLIA_ARTIFACT }}
          retention-days: 7

  # 如果您希望在文档包含错误时构建失败，请添加以下作业和artifacts/report.json上传文档步骤
  test:
    # 需要构建作业结果
    needs: build
    runs-on: ubuntu-latest

    steps:
      # 下载工件
      - name: Download artifacts
        uses: actions/download-artifact@v1
        with:
          name: docs
          path: artifacts

      # 测试文档
      - name: Test documentation
        uses: JetBrains/writerside-checker-action@v1
        with:
          instance: ${{ env.INSTANCE }}

  publish-indexes:
    # 需要构建作业结果
    needs: build
    runs-on: ubuntu-latest
    container:
      image: registry.jetbrains.team/p/writerside/builder/algolia-publisher:2.0.32-2

    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: algolia-indexes
      - uses: montudor/action-zip@v1
        with:
          args: unzip -qq ${{ env.ALGOLIA_ARTIFACT }} -d algolia-indexes
      - run: |
          env "algolia-key=${{env.ALGOLIA_KEY}}" java -jar /opt/builder/help-publication-agent.jar \
          update-index \
          --application-name ${{env.ALGOLIA_APP_NAME}} \
          --index-name ${{env.ALGOLIA_INDEX_NAME}} \
          --product ${{env.CONFIG_JSON_PRODUCT}} \
          --version ${{env.CONFIG_JSON_VERSION}} \
          --index-directory algolia-indexes/ \
          2>&1 | tee algolia-update-index-log.txt

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # 需要测试作业结果
    needs: test
    runs-on: ubuntu-latest
    steps:
      # 下载工件
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: docs
        # 解压工件
      - name: Unzip artifact
        uses: montudor/action-zip@v1
        with:
          args: unzip -qq ${{ env.ARTIFACT }} -d dir
        # 设置页面
      - name: Setup Pages
        uses: actions/configure-pages@v2
        # 上传工件
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: dir
        # 部署到GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1